apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::200385471840:role/eksctl-eks-cluster-nodegroup-eks-NodeInstanceRole-1FBZXKN2XLBT7
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::200385471840:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-29T07:41:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1040"
  uid: 21d8ad7e-b0ff-49fa-95c6-980b69f5e697